require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/api/**/*_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/requests/api/**/*_spec.rb
