default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: brvs_development

test:
  <<: *default
  database: brvs_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
