---
openapi: 3.0.1
info:
  title: Brvs REST API v1
  version: v1
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://{defaultHost}/oauth2/authorize
          tokenUrl: https://{defaultHost}/oauth2/token
          refreshUrl: https://{defaultHost}/oauth2/token
          scopes:
            users:read: Read user profile information
paths:
  "/api":
    get:
      summary: Retrieves API information and status
      security:
      - oauth2: []
      responses:
        '200':
          description: API available
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
